---
- name: Validar Pre-requisitos en Servidores Windows (Bucle Controlado)
  hosts: servidores_windows_via_jump # <--- CORRECTION: Target the actual inventory group
  gather_facts: false
  
  vars:
    puerto_base_tunel_local: 59850

  tasks:
    - name: "REPORTE: Inicializar listas de resultados"
      run_once: true
      delegate_to: localhost
      ansible.builtin.set_fact:
        hosts_exitosos: []
        hosts_fallidos: []
        lista_de_hosts: "{{ query('inventory_hostnames', 'servidores_windows_via_jump') }}"

    - name: "Procesar cada servidor del inventario"
      delegate_to: localhost # <--- CORRECTION: Delegate the entire loop block
      block:
        - include_tasks: process_server.yml
          loop: "{{ lista_de_hosts }}"
          loop_control:
            loop_var: current_host

    - name: "REPORTE FINAL: Generar artefacto con el resumen"
      run_once: true
      delegate_to: localhost
      ansible.builtin.set_stats:
        data:
          resumen_validacion:
            hosts_exitosos_total: "{{ hosts_exitosos | length }}"
            hosts_fallidos_total: "{{ hosts_fallidos | length }}"
            hosts_exitosos: "{{ hosts_exitosos }}"
            hosts_fallidos: "{{ hosts_fallidos }}"
