---
- name: Validar Pre-requisitos en Servidores Windows (Versión Definitiva y Consolidada)
  hosts: servidores_windows_via_jump
  gather_facts: false
  serial: 1
  ignore_unreachable: true
  
  vars:
    puerto_base_tunel_local: 59850

  tasks:
    # Tarea 1: Inicializar las listas UNA SOLA VEZ
    - name: "REPORTE: Inicializar listas de resultados"
      run_once: true
      delegate_to: localhost
      ansible.builtin.set_fact:
        cacheable: yes
        hosts_exitosos: []
        hosts_fallidos: []

    # Tarea 2: Bucle principal que procesa CADA host en localhost
    - name: "PROCESAR Y VALIDAR: {{ inventory_hostname }}"
      delegate_to: localhost
      block:
        # El cálculo del puerto ahora está DENTRO del bloque delegado
        - name: "CÁLCULO DE PUERTO para {{ inventory_hostname }}"
          ansible.builtin.set_fact:
            puerto_dinamico_tunel: "{{ puerto_base_tunel_local | int + ansible_play_hosts_all.index(inventory_hostname) | int }}"
        
        # Bloque interno para manejar el éxito o fallo de la conexión
        - name: "Conexión, Validación y Limpieza para {{ inventory_hostname }}"
          block:
            - name: "TUNNEL: Estableciendo túnel SSH para {{ inventory_hostname }}"
              ansible.builtin.command: >
                ssh -f -N -L {{ puerto_dinamico_tunel }}:{{ hostvars[inventory_hostname].target_actual_ip }}:{{ hostvars[inventory_hostname].target_actual_winrm_port }}
                -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ExitOnForwardFailure=yes
                -o ServerAliveInterval=60 -o ConnectTimeout=15
                {{ hostvars[inventory_hostname].jumphost_user }}@{{ hostvars[inventory_hostname].jumphost_ip }}
              changed_when: false

            - name: "TUNNEL: Esperar a que el puerto {{ puerto_dinamico_tunel }} esté activo"
              ansible.builtin.wait_for:
                host: 127.0.0.1
                port: "{{ puerto_dinamico_tunel }}"
                timeout: 20
                delay: 2
                state: started

            - name: "VALIDACIÓN WINDOWS: Conectividad WinRM en {{ inventory_hostname }}"
              ansible.windows.win_command: hostname
              vars:
                ansible_host: 127.0.0.1
                ansible_port: "{{ puerto_dinamico_tunel }}"
                ansible_user: "{{ hostvars[inventory_hostname].ansible_user }}"
                ansible_password: "{{ hostvars[inventory_hostname].ansible_password }}"
                ansible_connection: winrm
                ansible_winrm_transport: ntlm
                ansible_winrm_server_cert_validation: ignore
              register: windows_hostname_validation
              changed_when: false

            - name: "REPORTE ✅: Registrar host exitoso {{ inventory_hostname }}"
              ansible.builtin.set_fact:
                hosts_exitosos: "{{ hosts_exitosos + [{'host': inventory_hostname, 'ip': hostvars[inventory_hostname].target_actual_ip, 'hostname_remoto': windows_hostname_validation.stdout_lines[0]}] }}"
                
          rescue:
            - name: "REPORTE ❌: Registrar host fallido {{ inventory_hostname }}"
              ansible.builtin.set_fact:
                hosts_fallidos: "{{ hosts_fallidos + [{'host': inventory_hostname, 'ip': hostvars[inventory_hostname].target_actual_ip, 'error': ansible_failed_result.msg | default('Error desconocido.')}] }}"

          always:
            - name: "LIMPIEZA: Asegurando la terminación del túnel para {{ inventory_hostname }}"
              ansible.builtin.command: >
                pkill -f "ssh .* -L {{ puerto_dinamico_tunel }}:{{ hostvars[inventory_hostname].target_actual_ip }}:{{ hostvars[inventory_hostname].target_actual_winrm_port }}.*{{ hostvars[inventory_hostname].jumphost_user }}@{{ hostvars[inventory_hostname].jumphost_ip }}"
              changed_when: false
              failed_when: false
              
    # Tarea Final: Generar el artefacto UNA SOLA VEZ al final
    - name: "REPORTE FINAL: Generar artefacto con el resumen"
      run_once: true
      delegate_to: localhost
      ansible.builtin.set_stats:
        data:
          resumen_validacion:
            hosts_exitosos_total: "{{ hosts_exitosos | length }}"
            hosts_fallidos_total: "{{ hosts_fallidos | length }}"
            hosts_exitosos: "{{ hosts_exitosos }}"
            hosts_fallidos: "{{ hosts_fallidos }}"
