---
- name: Validar Pre-requisitos en Servidores Windows (Bucle Controlado)
  hosts: localhost
  gather_facts: false
  
  vars:
    puerto_base_tunel_local: 59850

  tasks:
    - name: "REPORTE: Inicializar listas de resultados"
      ansible.builtin.set_fact:
        hosts_exitosos: []
        hosts_fallidos: []

    - name: "Procesar cada servidor del inventario"
      include_tasks: process_server.yml
      loop: "{{ query('inventory_hostnames', 'servidores_windows_via_jump') }}"
      loop_control:
        loop_var: current_host

    - name: "REPORTE FINAL: Generar artefacto con el resumen"
      ansible.builtin.set_stats:
        data:
          resumen_validacion:
            hosts_exitosos_total: "{{ hosts_exitosos | length }}"
            hosts_fallidos_total: "{{ hosts_fallidos | length }}"
            hosts_exitosos: "{{ hosts_exitosos }}"
            hosts_fallidos: "{{ hosts_fallidos }}"
