- name: Prueba de copia para el filesystem local
  hosts: all
  become: false
  tasks:
  - name: Haciendo fetch del servidor unix al contenedor EE
    fetch:
      src: "{{ src_fetch }}"
      dest: "{{ dest_fetch }}"
      flat: yes
  - name: Copiando del Contenedor EE al filesystem Local
    copy:
      src: "{{ src_copy }}"
      dest: "{{ dest_copy }}"
    delegate_to: "{{ ip_dest }}"
