- name: Prueba de copia para el filesystem local
  hosts: all
  become: false
  tasks:
  - name: Haciendo fetch del servidor unix final al jumphost
    fetch:
      src: "{{ src_fetch }}"
      dest: "{{ dest_fetch }}"
      flat: yes
    delegate_to: "{{ ip_dest }}"
