- name: Traer archivo del Target Final al Entorno de Ejecución (EE)
  hosts: "{{ dispositivos_finales }}"
  gather_facts: false
  become: false
  tasks:
  - name: "Verificar que el archivo {{ nombre_archivo_a_tranferir }} existe en el servidor final"
    ansible.builtin.stat:
        path: "{{ruta_del_archivo}}/{{ nombre_archivo_a_tranferir }}"
    register: end_file_stat

  - name: "DEBUG: Info del archivo en servidor final"
    ansible.builtin.debug:
        msg: "Archivo a copiar desde el servidor final: {{ ruta_del_archivo }}. ¿Existe?: {{ end_file_stat.stat.exists | default(false) }}"
        
  - name: "Hacer Fetch del archivo '{{ nombre_archivo_a_tranferir }}' desde {{ inventory_hostname }} al EE"
    ansible.builtin.fetch:
        src: "{{ruta_del_archivo}}/{{ nombre_archivo_a_tranferir }}"
        dest: "{{ ruta_archivo_en_ee }}"
        flat: yes
    when: end_file_stat.stat.exists
- name: Copiar archivo del EE al filesystem del Host RHEL de AWX
  hosts: "{{ servidor_awx }}"
  gather_facts: false
  tasks:
  - name: "Verificar que el archivo {{ nombre_archivo_a_tranferir }} existe en el EE"
    ansible.builtin.stat:
       path: "{{ ruta_archivo_en_ee }}"
    register: ee_file_stat

  - name: "DEBUG: Info del archivo en EE"
    ansible.builtin.debug:
        msg: "Archivo a copiar desde EE: {{ ruta_archivo_en_ee }}. ¿Existe?: {{ ee_file_stat.stat.exists | default(false) }}"
  - name: "Copiar '{{ nombre_archivo_a_tranferir }}' del EE al Host RHEL"
    ansible.builtin.copy:
        src: "{{ ruta_archivo_en_ee }}"
        dest: "{{ ruta_destino_en_rhel }}/{{ nombre_archivo_a_tranferir }}"
        mode: '0644'
    when: end_file_stat.stat.exists
