- name: Traer archivo del Target Final al Entorno de Ejecución (EE)
  hosts: cg4_groibmrly01
  gather_facts: false
  become: false
  vars:
    ee_staging_path: "/runner/project/retrieved_artifact" 
    retrieved_file_name_in_ee: "{{ hostvars[inventory_hostname].ruta_del_archivo_a_recuperar | basename }}"
    ruta_del_archivo_a_recuperar: "/tmp/Kyndryl_19may2025_GROIBMRLY01.mef3"
  tasks:
  - name: "Crear directorio de staging en el EE"
    ansible.builtin.file:
        path: "{{ ee_staging_path }}"
        state: directory
    delegate_to: localhost
  - name: "Hacer Fetch del archivo '{{ hostvars[inventory_hostname].ruta_archivo_fuente_en_target }}' desde {{ inventory_hostname }} al EE"
    ansible.builtin.fetch:
        src: "{{ hostvars[inventory_hostname].ruta_del_archivo_a_recuperar }}"
        dest: "{{ ee_staging_path }}/"
        flat: yes
- name: Copiar archivo del EE al filesystem del Host RHEL de AWX
  hosts: localhost
  connection: local 
  gather_facts: false
  vars:
    awx_rhel_host_inventory_name: cg4_groibmrly01
    archivo_fuente_en_ee: "/runner/project/retrieved_artifact/Kyndryl_19may2025_GROIBMRLY01.mef3"
    destino_final_en_rhel: "/tmp/Kyndryl_19may2025_GROIBMRLY01.mef3" 
  tasks:
    - name: "Verificar que el archivo {{ archivo_fuente_en_ee }} existe en el EE"
      ansible.builtin.stat:
        path: "{{ archivo_fuente_en_ee }}"
      register: ee_file_stat

    - name: "DEBUG: Info del archivo en EE"
      ansible.builtin.debug:
        msg: "Archivo a copiar desde EE: {{ archivo_fuente_en_ee }}. ¿Existe?: {{ ee_file_stat.stat.exists | default(false) }}"

    - name: "Copiar '{{ archivo_fuente_en_ee }}' del EE al Host RHEL ({{ awx_rhel_host_inventory_name }})"
      ansible.builtin.copy:
        src: "{{ archivo_fuente_en_ee }}"
        dest: "{{ destino_final_en_rhel }}"
      delegate_to: "{{ awx_rhel_host_inventory_name }}"
  #    when: ee_file_stat.stat.is_file is defined and ee_file_stat.stat.is_file
