- name: Traer archivo del Target Final al Entorno de Ejecución (EE)
  hosts: cg4_groibmrly01
  gather_facts: false
  become: false
#  vars:
#    nombre_archivo_origen: "Kyndryl_19may2025_GROIBMRLY01.mef3"
#    ee_staging_path: "/tmp/{{ nombre_archivo_origen }}_fetched" 
#    ruta_del_archivo_a_recuperar: "/tmp/{{ nombre_archivo_origen }}"
  tasks:
  - name: "Hacer Fetch del archivo '{{ nombre_archivo_origen }}' desde {{ inventory_hostname }} al EE"
    ansible.builtin.fetch:
        src: "{{ ruta_del_archivo_a_recuperar }}"
        dest: "{{ ee_staging_path }}"
        flat: yes
- name: Copiar archivo del EE al filesystem del Host RHEL de AWX
  hosts: 10.72.1.47
  gather_facts: false
#  vars:
#    nombre_archivo_a_tranferir: "Kyndryl_19may2025_GROIBMRLY01.mef3"
#    ruta_archivo_en_ee: "/tmp/{{ nombre_archivo_a_tranferir }}_fetched"
#    ruta_destino_en_rhel: "/tmp/"
  tasks:
    - name: "Verificar que el archivo {{ nombre_archivo_a_tranferir }} existe en el EE"
      ansible.builtin.stat:
        path: "{{ ruta_archivo_en_ee }}"
      register: ee_file_stat

    - name: "DEBUG: Info del archivo en EE"
      ansible.builtin.debug:
        msg: "Archivo a copiar desde EE: {{ ruta_archivo_en_ee }}. ¿Existe?: {{ ee_file_stat.stat.exists | default(false) }}"

    - name: "Copiar '{{ nombre_archivo_a_tranferir }}' del EE al Host RHEL"
      ansible.builtin.copy:
        src: "{{ ruta_archivo_en_ee }}"
        dest: "{{ ruta_destino_en_rhel }}{{ nombre_archivo_a_tranferir }}"
        mode: '0644'
  #    when: ee_file_stat.stat.is_file is defined and ee_file_stat.stat.is_file
